#15: add `mean` and `std`
Pressio/pressio-linalg pull request #16
Opened 2024-02-15 14:44 UTC by cwschilly

Fixes #15

2024-02-15 15:07 UTC, fnrizzi commented on pressiolinalg/linalg.py
> +        global_mean = global_sum / n_procs
how is this right?!

```
proc0: 
  a = 1 2 3 4 
  local_mean = 10/4 = 2.5

proc1: 
  a = 5 6 7
  local_mean = 18/3 = 6

global_sum = 8.5
global_mean = 8.5/2 = 4.25

actual mean of data should be = 28/7 = 4
```

2024-02-15 17:36 UTC, cwschilly commented on pressiolinalg/linalg.py
> +        global_mean = global_sum / n_procs
Fixed, thanks!

2024-02-16 08:35 UTC, fnrizzi commented on pressiolinalg/linalg.py
> +            if global_min.ndim == 1:
why are these changed in this PR? these are in the other functions

2024-02-16 08:37 UTC, fnrizzi commented on pressiolinalg/linalg.py
> +        mean_dim = 1 if axis is None else a.ndim - 1 if isinstance(axis, int) else a.ndim - len(axis)
- what does `mean_dim` mean? 
- this line of code is duplicated for each function mean, max, min, etc. Since it is the same for all, please put it in a separate function

2024-02-16 08:39 UTC, fnrizzi commented on pressiolinalg/linalg.py
> +        comm.Allreduce(a, global_sum, op=MPI.SUM)
why are you reducing arrays here? we just need to compute the local sum and then reduce that

2024-02-16 08:41 UTC, fnrizzi commented on pressiolinalg/linalg.py
> +        std_dev = np.sqrt(global_sq_diff[0] / (global_size[0] - ddof))
similar comment as above

2024-02-16 08:42 UTC, fnrizzi commented on pressiolinalg/utils.py
> +def distribute_vector(global_vector, comm):
please document what this function does

2024-02-16 08:43 UTC, fnrizzi commented on pressiolinalg/utils.py
> +def distribute_array(global_array, comm):
please document what this function does

2024-02-16 08:43 UTC, fnrizzi commented on pressiolinalg/utils.py
> +def get_local_and_global_arrays(rank, comm):
please document in a comment here what this function does

2024-02-16 08:44 UTC, fnrizzi commented on pressiolinalg/utils.py
> +
what about the else?
please throw if we hit any other case

2024-02-16 08:45 UTC, fnrizzi requested changes
see my comments

2024-02-16 08:46 UTC, fnrizzi commented on pressiolinalg/linalg.py
> +            raise ValueError("The axis argument is not currently supported.")
two issues with this: 
- the message is not clear to me what it means 
- this same if/throw is repeated multiple times in the other functions. Please write a function for this with an expressive name and use that

2024-02-16 08:47 UTC, fnrizzi commented on pressiolinalg/linalg.py
> +            assert out.ndim == mean_dim, "out must have correct dimensions."
two issues with this: 
- the message is not clear to me what it means: `out`? what is out? what does it mean to have correct dimensions? when you write a thorw message it has to be as  informative as possible. You have to assume that the user does not know anything and they definitely do not want to look in the code to understand. 

- this same if/throw is repeated multiple times in the other functions. Please write a function for this with an expressive name and use that

2024-02-16 18:35 UTC, cwschilly commented on pressiolinalg/linalg.py
> +            if global_min.ndim == 1:
Since these old functions follow the same general structure as the new ones, as I've altered the mean/std functions I thought I should fix the min/max functions as well.

I can move these changes to a separate PR if that is preferable.

2024-02-16 18:37 UTC, cwschilly commented on pressiolinalg/linalg.py
> +        mean_dim = 1 if axis is None else a.ndim - 1 if isinstance(axis, int) else a.ndim - len(axis)
I've chosen to remove this code altogether for now, since it will only come into play once I add support for the `axis` argument. (since `axis` isn't used in romtools, I thought I would wait to add that support so we can merge [PR 126](https://github.com/Pressio/rom-tools-and-workflows/pull/126) asap).

2024-02-16 18:37 UTC, cwschilly commented on pressiolinalg/linalg.py
> +        comm.Allreduce(a, global_sum, op=MPI.SUM)
Mistake on my part; fixed.

2024-02-16 18:38 UTC, cwschilly commented on pressiolinalg/linalg.py
> +        std_dev = np.sqrt(global_sq_diff[0] / (global_size[0] - ddof))
Fixed

2024-02-16 18:38 UTC, cwschilly commented on pressiolinalg/utils.py
> +def distribute_vector(global_vector, comm):
Fixed

2024-02-16 18:38 UTC, cwschilly commented on pressiolinalg/utils.py
> +def distribute_array(global_array, comm):
Fixed

2024-02-16 18:38 UTC, cwschilly commented on pressiolinalg/utils.py
> +
Fixed

2024-02-16 18:39 UTC, cwschilly commented on pressiolinalg/linalg.py
> +            raise ValueError("The axis argument is not currently supported.")
I've removed `axis` from this PR for now--see above comment

2024-02-16 18:39 UTC, cwschilly commented on pressiolinalg/linalg.py
> +            assert out.ndim == mean_dim, "out must have correct dimensions."
Fixed (moved to `utils.py`)

2024-02-16 18:41 UTC, cwschilly commented on pressiolinalg/utils.py
> +def get_local_and_global_arrays(rank, comm):
Fixed

2024-02-19 15:06 UTC, fnrizzi requested changes
why did you put utils.py inside the main library? 
please put utils insie the test with only the functions needed in the test and then a different file inside the main library with the functions needed there

2024-02-19 15:08 UTC, fnrizzi commented on pressiolinalg/utils.py
> +def verify_out_size(out, expected_size):
if i read this function, it does not tell me anything about what the function is doing. 
a better is name would be: `assert_out_size_matches_expected`

2024-02-19 15:09 UTC, fnrizzi commented on pressiolinalg/utils.py
> +    '''Copies the result of an operation to the out array, if one is provided.'''
the function name you choose differs substnatially from the description you provide. 
if your func name is chosen more carefully, it would reflect better the description. please try to find a better name

2024-02-19 15:13 UTC, fnrizzi commented on pressiolinalg/utils.py
> +    '''Distributes a global vector over all available MPI processes.'''
this is incomplete, still does not say *how* this is disitrubted . I would need to read the function body to understand this.

2024-02-19 15:14 UTC, fnrizzi commented on pressiolinalg/utils.py
> +    '''Generates both local and global arrays for use in testing.'''
the function is called `get_` but the description says `generates`

2024-02-19 16:51 UTC, cwschilly commented on pressiolinalg/utils.py
> +def verify_out_size(out, expected_size):
Fixed

2024-02-19 16:52 UTC, cwschilly commented on pressiolinalg/utils.py
> +    '''Distributes a global vector over all available MPI processes.'''
Fixed.
For now, every rank gets the same number of elements. Once #17 is resolved this will not be the case

2024-02-19 16:52 UTC, cwschilly commented on pressiolinalg/utils.py
> +    '''Copies the result of an operation to the out array, if one is provided.'''
Fixed: `copy_result_to_out_if_given_else_return()`

2024-02-19 16:52 UTC, cwschilly commented on pressiolinalg/utils.py
> +    '''Generates both local and global arrays for use in testing.'''
Fixed: `get_local_and_global_arrays()`

2024-02-19 17:21 UTC, fnrizzi commented on pressiolinalg/utils.py
>      '''Copies the result of an operation to the out array, if one is provided.'''
i don't want to nitpick, but `out` here is always given. The function returns result is out is not none

2024-02-19 17:30 UTC, cwschilly commented on pressiolinalg/utils.py
>      '''Copies the result of an operation to the out array, if one is provided.'''
Fixed

2024-02-19 18:33 UTC, fnrizzi commented on pressiolinalg/linalg.py
> +        global_mean = global_sum / global_size
what if global_size is zero?

2024-02-19 18:51 UTC, fnrizzi commented on pressiolinalg/linalg.py
> +        global_mean = global_sum / global_size
what does np.mean compute if size is 0?

2024-02-19 18:58 UTC, cwschilly commented on pressiolinalg/linalg.py
> +        global_mean = global_sum / global_size
This error:
```
>>> import numpy as np
>>> np.mean(np.empty(0))
/home/calebschilly/miniconda3/envs/pressio-linalg/lib/python3.11/site-packages/numpy/core/fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/calebschilly/miniconda3/envs/pressio-linalg/lib/python3.11/site-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
nan
```

2024-02-19 19:02 UTC, fnrizzi commented on pressiolinalg/linalg.py
> +        global_mean = global_sum / global_size
so it is a warning not an error?

2024-02-19 20:11 UTC, cwschilly commented on pressiolinalg/linalg.py
> +        global_mean = global_sum / global_size
Right; should I recreate this (ie return a nan instead of throwing an error)?

2024-02-20 09:15 UTC, fnrizzi commented on pressiolinalg/linalg.py
> +        local_size = a.size
why are you using size here?

2024-02-20 14:15 UTC, cwschilly commented on pressiolinalg/linalg.py
> +        local_size = a.size
Get the total number of elements in the local array, then sum across processes to get the total number of elements in the global array (so I can then calculate the mean as `global_sum / global_size`).

The diff here is kind of misleading (I didn't delete this `local_min` line--it's up at line 57)

2024-03-04 07:53 UTC, fnrizzi commented on pressiolinalg/utils.py
> +            assert axis <= a.ndim
this is wrong: axis < a.dim. 
I think i commented on this before or even changed it directly, did you not see it?

2024-03-04 07:54 UTC, fnrizzi commented on pressiolinalg/utils.py
> +            assert axis <= a.ndim
i am fixing some things anyway so dont change it

2024-03-04 08:13 UTC, fnrizzi approved these changes

2024-03-04 08:13 UTC, merged